import { useState } from 'react';
import { Button, ListRow, SegmentedControl } from '@toss/tds-mobile';
import type { Account, Position, State } from './types';
import { accountLabels } from './types';
import { exampleState, defaultPosition } from './state';
import { portfolio, targetExpense, toIncome } from './engine';
import { calculateTax } from './tax';
import { Amount, fmt, Icon, money, MonthsChart, Notice, pct, Row, Section, Title } from './components';
export function Dashboard({ state:s, update, editPosition, editAccount }: { state:State; update(s:State):void; editPosition(p?:Position):void; editAccount(a?:Account):void }) {
  const result = portfolio(s), expense = targetExpense(s), coverage = expense && expense > 0 ? result.usable / (expense*12) : 0;
  const [quick,setQuick] = useState({ domestic:0,foreign:0,interest:0 }), [quickResult,setQuickResult] = useState<ReturnType<typeof calculateTax> | null>(null);
  const [chartMode,setChartMode]=useState('expected');
  const actualMonths=Array.from({length:12},(_,i) => ({month:i+1,cash:0}));
  const actualReceipts=s.receipts.filter(r => Number(r.date.slice(0,4))===s.tax.year && (r.accountKind ?? s.accounts.find(a => a.id===s.positions.find(p => p.id===r.positionId)?.accountId)?.kind)==='taxable');
  actualReceipts.forEach(r => { actualMonths[Number(r.date.slice(5,7))-1].cash+=r.gross-r.foreignTax-r.nationalTax-r.localTax; });
  return <>
    <div className="page-intro"><span className="eyebrow">내 배당</span><span className="year-badge">{s.tax.year}년 예상</span></div><Title title="배당으로 채우는 생활비" subtitle="원금을 팔지 않고, 세후 배당으로 계산해요." />
    <div className="hero"><span className="hero-label">세후 월평균 사용 가능액</span><div className="hero-amount" data-testid="monthly-income">{money(result.usable/12)}</div><p>{s.fire.healthMode === 'exclude' ? '건강보험료를 제외한 결과예요' : s.fire.healthMonthly === null ? '건강보험료를 입력해 주세요' : `건강보험료 월 ${money(s.fire.healthMonthly)}을 포함해요`}</p><div className="coverage"><div><span>생활비 충당률</span><strong>{pct(coverage)}</strong></div><div className="progress-track"><div style={{ width:`${Math.min(100,Math.max(0,coverage*100))}%` }} /></div><span>월 목표 {expense === null ? '입력 필요' : money(expense)}</span></div>{!result.tax.complete && <Notice warning>원천징수 후 예상액이에요. 종합과세 정산을 계산하려면 상세 세금 정보를 입력해 주세요.</Notice>}</div>
    {!s.positions.length && <div className="empty"><div className="empty-icon"><Icon kind="income" /></div><h2>첫 배당 자산을 등록해요</h2><p>금액을 직접 입력하거나<br />예시로 계산 흐름을 살펴볼 수 있어요.</p><Button display="block" size="large" onClick={() => editPosition()}>종목 추가하기</Button><button className="text-button" onClick={() => update(exampleState())}>예시로 체험하기</button><p className="help">예시는 가상 자산이에요. 실제 종목 추천이나 수익 전망이 아니에요.</p></div>}
    <Section title="지급월별 배당"><div className="inset"><SegmentedControl value={chartMode} onChange={setChartMode}><SegmentedControl.Item value="expected">예상 배당</SegmentedControl.Item><SegmentedControl.Item value="actual">실제 수령 기록</SegmentedControl.Item></SegmentedControl></div><MonthsChart months={chartMode==='actual' ? actualMonths : result.months} actual={chartMode==='actual'} />{chartMode==='actual' && actualReceipts.length===0 && <p className="help inset">아직 이 귀속연도의 일반계좌 수령 기록이 없어요. 세금·신고 탭에서 실제 지급일과 금액을 입력해 주세요.</p>}<p className="help inset">월평균과 실제 지급월은 달라요. 연금 인출·종합과세 정산은 이 차트에 포함하지 않아요.</p></Section>
    <Section title="내 포트폴리오"><Row label="총 투자금" value={money(result.value)} /><Row label="세전 연간 배당" value={money(result.gross)} /><Row label="생활비로 쓸 수 있는 연간 금액" value={money(result.usable)} />{s.positions.map(p => <ListRow key={p.id} border="indented" onClick={() => editPosition(p)} left={<span className="asset-icon">{p.market === 'US' ? '$' : '₩'}</span>} contents={<div className="row-label"><strong>{p.name}</strong><small>{s.accounts.find(a => a.id === p.accountId)?.name} · {fmt(p.quantity)}주</small></div>} right={<div className="row-value">{money(p.dividend*p.quantity*(p.market === 'US' ? s.fx : 1))}<small>연간 세전</small></div>} />)}{s.positions.length > 0 && <div className="inset"><Button display="block" variant="weak" onClick={() => editPosition()}>종목 추가하기</Button></div>}<details><summary>계좌·환율 관리하기</summary><div className="inset"><Amount label="고정 원·달러 환율" unit="원/USD" value={s.fx} onChange={v => { if (v && v > 0) update({ ...s,fx:v }); }} /></div>{s.accounts.map(a => <ListRow key={a.id} onClick={() => editAccount(a)} contents={<div className="row-label">{a.name}<small>{accountLabels[a.kind]}</small></div>} right="수정 ›" />)}<div className="inset"><Button display="block" variant="weak" color="dark" onClick={() => editAccount()}>계좌 추가하기</Button></div></details>{result.locked.map((a,i) => <div className="inset" key={i}><Notice><strong>{a.name}</strong> · 연 {money(a.gross)} 제외<br />{a.note}{a.settlement && <p>누적 정산 대상 이익 {money(a.settlement.netProfit)} · 예상 세금 {money(a.settlement.tax)}</p>}</Notice></div>)}</Section>
    <Section title="금액으로 빠르게 계산해요"><div className="form compact"><Amount label="국내 배당 · 연간 세전" value={quick.domestic} onChange={v => setQuick({ ...quick,domestic:v ?? 0 })} /><Amount label="미국 배당 · 연간 세전 원화" value={quick.foreign} onChange={v => setQuick({ ...quick,foreign:v ?? 0 })} /><Amount label="이자 · 연간 세전" value={quick.interest} onChange={v => setQuick({ ...quick,interest:v ?? 0 })} /><Button display="block" onClick={() => { const domestic = defaultPosition('general'); setQuickResult(calculateTax([toIncome(domestic,quick.domestic),toIncome({ ...domestic,market:'US' },quick.foreign)], { ...s.tax,interest:quick.interest })); }}>배당 계산하기</Button>{quickResult && <Notice><strong>원천징수 후 {money(quickResult.withholdingNet)}</strong><p>{quickResult.reason}</p>{quickResult.complete ? `정산 반영 사용 가능액 ${money(quickResult.usable)}` : '최종 세금 계산 미완료 · 세금 탭에서 상세 정보를 입력해 주세요.'}</Notice>}<p className="help">일반계좌·미국 원천징수 15%·국내 증권사 절차를 가정해요. 포트폴리오에는 추가되지 않아요.</p></div></Section>
  </>;
}
