import { useState } from 'react';
import { Button, TextField } from '@toss/tds-mobile';
import type { Account, Position, Receipt, State } from './types';
import { accountLabels } from './types';
import { positionError } from './engine';
import { dividendLookupAvailable, lookupDividend, type DartDividend } from './data';
import { openUrl } from './platform';
import { Amount, Check, money, Notice, Select, Title } from './components';
interface EditorProps<T> { state: State; initial: T; onDone(value: T): void; onClose(): void; onError(message: string): void; onRemove?():void }
export function PositionEditor({ state: s, initial, onDone, onClose, onError, onRemove }: EditorProps<Position>) {
  const [p, setP] = useState(initial), [corp, setCorp] = useState(''), [year, setYear] = useState(s.tax.year - 1), [kind, setKind] = useState('보통주');
  const [lookup, setLookup] = useState<DartDividend | null>(null), [busy, setBusy] = useState(false);
  const change = (value: Partial<Position>) => setP({ ...p,...value });
  return <main><Title title={s.positions.some(v => v.id === p.id) ? '종목을 수정해요' : '배당 자산을 추가해요'} subtitle="가격·연간 주당 배당은 선택한 통화로 입력해요." /><div className="form">
    <TextField variant="box" label="종목 이름" labelOption="sustain" aria-label="종목 이름" value={p.name} onChange={e => change({ name:e.target.value })} />
    <TextField variant="box" label="종목코드 / 티커" labelOption="sustain" aria-label="종목코드 / 티커" value={p.ticker} onChange={e => change({ ticker:e.target.value })} />
    <Select label="계좌" value={p.accountId} onChange={v => change({ accountId:v })} options={s.accounts.map(a => [a.id,a.name])} />
    <div className="two-cols"><Select label="상장 시장·통화" value={p.market} onChange={v => change({ market:v as Position['market'],source:undefined,manuallyEdited:true })} options={ [['KR','국내 · KRW'],['US','미국 · USD']] } /><Select label="상품 종류" value={p.instrument} onChange={v => change({ instrument:v as Position['instrument'] })} options={ [['stock','주식'],['etf','ETF']] } /></div>
    {s.accounts.find(a => a.id === p.accountId)?.kind !== 'taxable' && <Check checked={p.accountEligible} onChange={v => change({ accountEligible:v })}>증권사에서 이 계좌에 편입 가능한 상품임을 확인했어요</Check>}
    {p.instrument === 'etf' && <Check checked={p.leveraged} onChange={v => change({ leveraged:v })}>레버리지·인버스 상품이에요</Check>}
    {s.accounts.find(a => a.id === p.accountId)?.kind === 'irp' && <Select label="IRP 편입 한도 구분 (증권사 기준)" value={p.pensionRisk} onChange={v => change({ pensionRisk:v as Position['pensionRisk'] })} options={ [['risky','위험자산 · 70% 한도'],['safe','100% 편입 가능 상품']] } />}
    <Amount label="보유 수량" unit="주" value={p.quantity} onChange={v => change({ quantity:v ?? 0 })} />
    <Amount label="현재 주당 가격" unit={p.market === 'US' ? '달러' : '원'} value={p.price} onChange={v => change({ price:v ?? 0 })} />
    <Amount label="연간 주당 배당금" unit={p.market === 'US' ? '달러' : '원'} value={p.dividend} onChange={v => change({ dividend:v ?? 0,manuallyEdited:true })} />
    {p.source && <p className="help">{p.source.year}년 {p.source.stockKind} 공시 · 조회 {p.source.asOf.slice(0,10)}{p.manuallyEdited ? ' · 직접 수정한 값' : ''}<button className="text-button" onClick={() => openUrl(p.source!.url)}>출처 확인하기</button></p>}
    <fieldset className="months"><legend>배당 지급월 · 선택한 달에 균등 배분해요</legend>{Array.from({ length:12 },(_,i) => i+1).map(m => <button key={m} type="button" aria-pressed={p.months.includes(m)} onClick={() => change({ months:p.months.includes(m) ? p.months.filter(v => v !== m) : [...p.months,m].sort((a,b) => a-b) })}>{m}월</button>)}</fieldset>
    <Select label="배당 과세 구분" value={p.taxClass} onChange={v => change({ taxClass:v as Position['taxClass'] })} options={ [['ordinary','일반 합산 대상'],['exempt','비과세 (증빙 확인)'],['separate','별도 분리과세 (증빙 확인)'],['high','고배당기업 특례']] } />
    {p.taxClass === 'separate' && <Amount label="분리과세 국세 세율" unit="%" max={100} value={p.separateRate} onChange={v => change({ separateRate:v ?? 0 })} />}
    {p.market === 'US' ? <><Amount label="외국 원천징수 세율" unit="%" max={100} value={p.foreignRate} onChange={v => change({ foreignRate:v ?? 0 })} /><Check checked={p.domesticProcedure} onChange={v => change({ domesticProcedure:v })}>국내 증권사의 원천징수 절차를 거쳐요</Check><p className="help">외국 세금이 국내 국세율보다 크면 국내 원천징수 예상액은 0원이에요. 절차 유무와 세액 0원은 달라요.</p></> : <Check checked={p.grossUp} onChange={v => change({ grossUp:v })}>명세서에서 배당가산·배당세액공제 대상임을 확인했어요</Check>}
    {p.taxClass === 'high' && <><Notice>2028년 12월 31일이 속한 사업연도까지 발생한 대상 기업 현금배당이에요. 12월 결산기업의 2028년 배당을 2029년에 받는 경우도 확인해 주세요. 높은 배당률만으로 자격을 판단하지 않아요.</Notice><TextField variant="box" label="특례 자격 증빙 / 공시" labelOption="sustain" aria-label="특례 자격 증빙 / 공시" value={p.highEvidence} onChange={e => change({ highEvidence:e.target.value })} /><Amount label="특례 마지막 적용 수령연도 (증빙 기준)" unit="년" max={2030} value={p.highThroughYear} onChange={v => change({highThroughYear:v ?? 2029})} /><Check checked={p.highElected} onChange={v => change({ highElected:v })}>분리과세를 신청하는 조건으로 계산해요</Check></>}
    {dividendLookupAvailable && p.market === 'KR' && p.instrument === 'stock' && <details><summary>DART 공시 배당 조회하기</summary><p className="help">연간 보고서의 현재연도 배당을 조회해요. 기업·주식 종류를 확인한 뒤 적용해 주세요.</p><TextField variant="box" label="DART 고유번호 8자리" labelOption="sustain" aria-label="DART 고유번호 8자리" inputMode="numeric" value={corp} onChange={e => setCorp(e.target.value)} /><Amount label="공시 사업연도" unit="년" value={year} onChange={v => setYear(v ?? s.tax.year-1)} /><Select label="공시 주식 종류" value={kind} onChange={setKind} options={ [['보통주','보통주'],['우선주','우선주']] } /><Button variant="weak" color="dark" disabled={busy} onClick={async () => { setBusy(true); try { setLookup(await lookupDividend(corp,year,kind)); } catch (e) { onError((e as Error).message); } finally { setBusy(false); } }}>{busy ? '조회하고 있어요' : '배당 조회하기'}</Button><button className="text-button" onClick={() => openUrl('https://dart.fss.or.kr')}>DART에서 기업·공시 확인하기</button>{lookup && <Notice>{lookup.company} · {lookup.year}년 · {lookup.stockKind}<br />주당 {money(lookup.amount)}<Button variant="weak" onClick={() => { change({ dividend:lookup.amount,source:lookup,manuallyEdited:false }); setLookup(null); }}>확인한 배당 적용하기</Button></Notice>}</details>}
    <Button size="large" display="block" onClick={() => { const error = positionError(p,s.accounts.find(a => a.id === p.accountId)); if (error) onError(error); else onDone(p); }}>종목 반영하기</Button>
    <Button variant="weak" color="dark" display="block" onClick={onClose}>닫기</Button>
    {s.positions.some(v => v.id === initial.id) && <button className="text-button danger" onClick={onRemove}>종목 삭제하기</button>}
  </div></main>;
}
export function AccountEditor({ state: s, initial, onDone, onClose, onError, onRemove }: EditorProps<Account>) {
  const [a,setA] = useState(initial), change = (value: Partial<Account>) => setA({ ...a,...value });
  return <main><Title title="계좌 조건을 입력해요" subtitle="계좌 안의 수익과 꺼낼 수 있는 금액을 구분해요." /><div className="form">
    <TextField variant="box" label="계좌 이름" labelOption="sustain" aria-label="계좌 이름" value={a.name} onChange={e => change({ name:e.target.value })} /><Select label="계좌 종류" value={a.kind} onChange={v => change({ kind:v as Account['kind'] })} options={Object.entries(accountLabels)} />
    {a.kind !== 'taxable' && <Amount label="계좌 개설연도" value={a.openedYear} unit="년" onChange={v => change({ openedYear:v ?? s.tax.year })} />}
    {a.kind !== 'taxable' && <Amount label="올해 추가 납입 가능액 (이월 포함)" value={a.contributionRemaining} onChange={v => change({ contributionRemaining:v ?? 0 })} />}
    {a.kind === 'isa' && <Amount label="ISA 총 납입한도 잔여액" value={a.isaLifetimeRemaining} onChange={v => change({ isaLifetimeRemaining:v ?? 0 })} />}
    {a.kind === 'isa' && <><Amount label="만기 정산연도" unit="년" value={a.settlementYear} onChange={v => change({ settlementYear:v ?? s.tax.year })} /><Select label="계좌 비과세 한도" value={String(a.isaExemption)} onChange={v => change({ isaExemption:Number(v) })} options={ [['2000000','일반형 · 누적 200만 원'],['4000000','서민형·농어민형 · 누적 400만 원']] } /><Amount label="이번 연도 이전 누적 이익" value={a.cumulativeProfit} onChange={v => change({ cumulativeProfit:v ?? 0 })} /><Amount label="손익통산 대상 누적 손실" value={a.cumulativeLoss} onChange={v => change({ cumulativeLoss:v ?? 0 })} /><Notice>비과세 한도는 매년 새로 생기지 않아요. 정산까지 생활비에서 제외하고 다음 해부터 일반계좌로 운용한다고 가정해요. 펀드 내부의 외국세액은 실제 정산자료를 확인해 주세요.</Notice></>}
    {(a.kind === 'pension' || a.kind === 'irp') && <><Amount label="현재 나이" unit="세" value={a.pensionAge} onChange={v => change({ pensionAge:v ?? 0 })} /><Amount label="현재 연금수령 연차" unit="년차" value={a.pensionYear} onChange={v => change({ pensionYear:v ?? 1 })} /><Amount label="세액공제 받지 않은 납입금 잔액" value={a.afterTaxPrincipal} onChange={v => change({ afterTaxPrincipal:v ?? 0 })} /><Amount label="연간 예정 인출액" value={a.annualWithdrawal} onChange={v => change({ annualWithdrawal:v ?? 0 })} /><Check checked={a.deferredRetirement} onChange={v => change({ deferredRetirement:v })}>퇴직급여 이연분이 포함돼 있어요</Check><Notice>배당 범위에서만 인출해요. 연금수령 조건·한도를 적용하며 과세대상 사적연금 연 1,500만 원 초과 시 16.5% 분리과세 선택을 가정해요. 종신형 계약과 퇴직급여 이연분의 세액은 지원하지 않아요.</Notice></>}
    <Button display="block" size="large" onClick={() => { const invalid = s.positions.filter(p => p.accountId === a.id).map(p => positionError(p,a)).find(Boolean); if (!a.name.trim() || !Number.isInteger(a.pensionYear) || a.pensionYear < 1 || !Number.isInteger(a.openedYear) || a.openedYear > s.tax.year || a.isaLifetimeRemaining>100000000 || a.contributionRemaining>a.isaLifetimeRemaining && a.kind==='isa' || (a.kind==='pension' || a.kind==='irp') && a.contributionRemaining>18000000 || (a.kind === 'isa' && a.settlementYear - a.openedYear < 3) || invalid) onError(invalid || '계좌 이름·연도·납입 한도를 확인해 주세요. ISA는 가입 3년 이상을 가정해요.'); else onDone(a); }}>계좌 반영하기</Button><Button variant="weak" color="dark" display="block" onClick={onClose}>닫기</Button>
    {s.accounts.some(v => v.id===initial.id) && <button className="text-button danger" onClick={onRemove}>빈 계좌 삭제하기</button>}
  </div></main>;
}
export function ReceiptEditor({ state:s, initial, onDone, onClose, onError, onRemove }: EditorProps<Receipt>) {
  const [r,setR] = useState(initial);
  return <main><Title title="실제 수령액을 기록해요" subtitle="지급명세서 기준 원화 금액으로 입력해요." /><div className="form"><Select label="수령한 종목" value={r.positionId} onChange={v => setR({ ...r,positionId:v })} options={s.positions.map(p => [p.id,p.name])} /><label className="select"><span>실제 지급일</span><input aria-label="실제 지급일" type="date" value={r.date} onChange={e => setR({ ...r,date:e.target.value })} /></label>{(['gross','foreignTax','nationalTax','localTax'] as const).map((key,i) => <Amount key={key} label={['세전 배당금','외국에서 낸 세금','국내 국세 원천징수','국내 지방세 원천징수'][i]} value={r[key]} onChange={v => setR({ ...r,[key]:v ?? 0 })} />)}<Button display="block" size="large" onClick={() => { if (!r.date || !s.positions.some(p => p.id === r.positionId) || r.foreignTax+r.nationalTax+r.localTax > r.gross) onError('지급일과 세금 합계를 확인해 주세요.'); else onDone(r); }}>수령 기록 반영하기</Button><Button display="block" variant="weak" color="dark" onClick={onClose}>닫기</Button>{s.receipts.some(v => v.id===initial.id) && <button className="text-button danger" onClick={onRemove}>수령 기록 삭제하기</button>}</div></main>;
}
