import { useMemo } from 'react';
import type { State } from './types';
import { requiredCapital, simulate } from './engine';
import { Amount, FireChart, fmt, money, Notice, pct, Row, Section, Select, Title } from './components';
export function Fire({ state:s,update }: { state:State; update(s:State):void }) {
  const fire = useMemo(() => simulate(s),[s]), required = useMemo(() => requiredCapital(s),[s]);
  const change = (fields:Partial<State['fire']>) => update({ ...s,fire:{ ...s.fire,...fields } });
  return <><div className="page-intro"><span className="eyebrow">FIRE</span><span className="year-badge">원금 매도 없이</span></div><Title title="배당만으로 생활할 때까지" subtitle="현재 자산 비중으로 투자·재투자한다고 가정해요." /><div className="hero"><span className="hero-label">목표 달성 예상</span><div className="hero-amount">{fire.reached ? `${fire.reached}년` : '목표 미달'}</div><p>{fire.reached ? `${fire.reached-s.tax.year}년 후 · 월 생활비 전액 충당` : `${s.fire.horizon}년 내 목표를 충족하지 못했어요`}</p><div className="hero-divider"/><span className="hero-label">현재 배당률 기준 필요 투자금</span><strong className="secondary-amount">{required.value === null ? '계산을 완료해 주세요' : money(required.value)}</strong><p>{s.fire.healthMode === 'exclude' ? '건강보험료를 제외한 결과예요' : s.fire.healthMonthly === null ? '건강보험료를 입력해 주세요' : `건강보험료 월 ${money(s.fire.healthMonthly)}을 포함해요`}</p></div>{required.value === null && <div className="inset"><Notice warning>{required.reason}</Notice></div>}{fire.incomplete && <div className="inset"><Notice warning>기간 중 종합과세 계산 정보가 부족해요. 원천징수 추정액을 표시하며 목표 달성 판단은 보류해요.</Notice></div>}
    {fire.points.length > 0 && <Section title="시간에 따른 생활비 충당률"><FireChart points={fire.points}/><p className="help inset">달성 후 추가 투자·재투자를 중단해요.{fire.reached === null ? ' 아직 목표에 도달하지 못했어요.' : fire.deteriorates ? ' 이후 충당률이 100% 아래로 떨어지는 해가 있어요.' : ' 입력한 기간에서는 이후 100% 아래로 떨어지지 않아요.'}</p><details><summary>연도별 금액 확인하기</summary>{fire.points.map(p => <Row key={p.year} label={`${p.year}년 · ${pct(p.coverage)}`} value={money(p.usable)} note={`연간 목표 ${money(p.expense)}`} />)}</details></Section>}
    {fire.uninvested > 0 && <div className="inset"><Notice>계좌 납입·IRP 편입 한도로 투자하지 않은 누적 금액 {money(fire.uninvested)}은 현금으로 남겨 배당 계산에서 제외했어요.</Notice></div>}
    <Section title="생활비와 투자 조건"><div className="form compact"><Amount label="목표 월 생활비" value={s.fire.expense} onChange={v => change({ expense:v ?? 0 })} /><Select label="건강보험료 계산 방식" value={s.fire.healthMode} onChange={v => change({ healthMode:v as State['fire']['healthMode'] })} options={ [['exclude','건강보험료 제외'],['manual','건강보험료 직접 입력']] } />{s.fire.healthMode === 'manual' ? <Amount label="월 건강보험료" value={s.fire.healthMonthly} onChange={v => change({ healthMonthly:v })} /> : <p className="help">보험료가 0원이라는 뜻은 아니에요. 입력한 금액은 보존돼요.</p>}<Amount label="매월 추가 투자금" value={s.fire.contribution} onChange={v => change({ contribution:v ?? 0 })} /><Amount label="배당 재투자 비율" unit="%" max={100} value={s.fire.reinvest} onChange={v => change({ reinvest:v ?? 0 })} /><Amount label="연간 물가상승률" unit="%" max={30} value={s.fire.inflation} onChange={v => change({ inflation:v ?? 0 })} /><Amount label="연간 배당 증가율" unit="%" signed max={50} value={s.fire.dividendGrowth} onChange={v => { if ((v ?? 0) >= -50) change({ dividendGrowth:v ?? 0 }); }} /><Amount label="연간 가격 변화율" unit="%" signed max={50} value={s.fire.priceGrowth} onChange={v => { if ((v ?? 0) >= -50) change({ priceGrowth:v ?? 0 }); }} /><Amount label="시뮬레이션 기간" unit="년" max={50} value={s.fire.horizon} onChange={v => { if (v && Number.isInteger(v) && v >= 1) change({ horizon:v }); }} /></div></Section>
    <Section title="계산에 적용한 가정"><div className="inset"><Notice>환율 {fmt(s.fx)}원 고정 · 추가 투자는 월말 · 소수점 수량 매수 가능 · 지급월에 균등 배당을 가정해요. 그래프는 연초 자산의 연간 배당을 기준으로 해요. 다른 소득·공제·외국공제 대상액은 입력값을 유지해요. 현행 세율을 반복 적용하며 2027년 배당가산율 변경·입력한 사업연도·수령연도에 따른 특례 종료를 반영해요. 미래 법 개정·거래비용·배당 중단은 예측하지 않아요. 수익과 원금 가치를 보장하지 않아요.</Notice><Notice>ISA 정산연도에는 배당을 유보해 누적 정산세액을 먼저 차감해요. 그 해 배당으로 세금을 낼 수 없으면 원금을 팔지 않는 조건의 계산을 완료하지 않아요. 다음 해부터 일반계좌로 운용해요. 연금 납입금의 추가 세액공제는 예측하지 않아요.</Notice><p className="help">{required.reason}</p></div></Section>
  </>;
}
