import { Button, ListRow } from '@toss/tds-mobile';
import type { Receipt, State } from './types';
import { portfolio, toIncome } from './engine';
import { calculateTax, TAX_VERSION } from './tax';
import { openUrl } from './platform';
import { filingSteps, sources } from './content';
import { Amount, Check, money, Notice, Row, Section, Select, Title } from './components';
export function Tax({ state:s, update, editReceipt }: { state:State; update(s:State):void; editReceipt(r?:Receipt):void }) {
  const result = portfolio(s), t = result.tax;
  const change = (fields:Partial<State['tax']>) => update({ ...s,tax:{ ...s.tax,...fields } });
  const actualIncome = s.receipts.filter(r => Number(r.date.slice(0,4)) === s.tax.year).flatMap(r => { const p = s.positions.find(p => p.id === r.positionId)!; if ((r.accountKind ?? s.accounts.find(a => a.id === p.accountId)?.kind) !== 'taxable') return []; return [{ ...(r.incomeSnapshot ?? toIncome(p,r.gross)),gross:r.gross,foreignTax:r.foreignTax,nationalPaid:r.nationalTax,localPaid:r.localTax }]; });
  const actualTax = calculateTax(actualIncome,s.tax);
  const fields: [keyof State['tax'],string][] = [['otherIncome','다른 종합소득금액 (총급여가 아니에요)'],['deductions','소득공제 합계'],['nationalCredits','국세 세액공제 (배당·외국 공제 제외)'],['localCredits','지방세 세액공제 (외국 공제 제외)'],['otherNationalPaid','다른 소득의 국세 기납부액'],['otherLocalPaid','다른 소득의 지방세 기납부액'],['foreignEligibleTax','공제 대상 외국납부세액'],['foreignLocalCredit','증빙으로 확인한 지방세 외국공제액']];
  return <><div className="page-intro"><span className="eyebrow">세금·신고</span><span className="year-badge">{s.tax.year}년 귀속</span></div><Title title="배당 세금을 확인해요" subtitle="한국 거주자 개인 · 입력한 범위의 추정값이에요." />
    <div className="hero"><span className="hero-label">합산 대상 세전 이자·배당</span><div className="hero-amount">{money(t.financial)}</div><p>{t.financial > 20000000 ? `2,000만 원보다 ${money(t.financial-20000000)} 많아요` : `2,000만 원까지 ${money(20000000-t.financial)} 남았어요`}</p><Notice warning={t.reporting}>{t.reason}</Notice></div>
    <Section title="원천징수와 예상 정산"><Row label="외국 원천징수" value={money(t.foreign)} /><Row label="국내 국세 원천징수" value={money(t.nationalPaid)} /><Row label="국내 지방세 원천징수" value={money(t.localPaid)} /><Row label="배당으로 늘어난 국세" value={t.incrementalNational === null ? '계산 미완료' : money(t.incrementalNational)} /><Row label="배당으로 늘어난 지방세" value={t.incrementalLocal === null ? '계산 미완료' : money(t.incrementalLocal)} /><Row label="국세 예상 추가 납부 / 환급" value={t.settlementNational === null ? '계산 미완료' : money(t.settlementNational)} note="다른 소득·이자 포함 전체 정산 · 음수는 환급 추정" /><Row label="지방세 예상 추가 납부 / 환급" value={t.settlementLocal === null ? '계산 미완료' : money(t.settlementLocal)} /><div className="inset">{t.missing.map(m => <Notice key={m} warning>{m}</Notice>)}</div><details><summary>비교과세·공제 근거 보기</summary><Row label="일반 산출세액 A" value={money(t.a)} /><Row label="비교 산출세액 B" value={money(t.b)} /><Row label="배당가산액" value={money(t.grossUp)} /><Row label="배당세액공제" value={money(t.dividendCredit)} /><Row label="외국납부세액 공제 한도" value={money(t.foreignLimit)} /><Row label="적용한 외국납부세액공제" value={money(t.foreignCredit)} /><p className="inset help">생활비에서는 다른 소득 자체의 세금을 빼지 않아요. 이자만 있는 경우와 배당을 합친 경우의 세금 차이를 사용해요. 이월 외국세액·특수 금융소득은 포함하지 않아요.</p></details></Section>
    <Section title="상세 세금 입력"><div className="form compact"><Select label="귀속연도" value={String(s.tax.year)} onChange={v => change({ year:Number(v) })} options={ [['2026','2026년'],['2027','2027년'],['2028','2028년'],['2029','2029년 · 현행법 가정'],['2030','2030년 · 현행법 가정']] } /><Amount label="다른 계좌 포함 세전 이자소득" value={s.tax.interest} onChange={v => change({ interest:v ?? 0 })} />{fields.map(([key,label]) => <Amount key={key} label={label} value={s.tax[key] as number | null} onChange={v => change({ [key]:v })} />)}<Check checked={s.tax.confirmed} onChange={v => change({ confirmed:v })}>모든 소득·공제·기납부액을 확인했어요. 없는 항목도 0원을 입력했어요.</Check><Notice>미국 직접 수령 배당의 외국세액 공제 추정을 지원해요. 지방세 외국공제액은 증빙으로 확인해 입력해 주세요. 국내 ETF 내부 외국세액·국가별 이월공제·비영업대금 이자·출자공동사업 배당·사업소득의 별도 비교과세 등은 지원하지 않아요.</Notice></div></Section>
    <Section title="실제 수령 기록"><p className="inset help">예상 포트폴리오와 분리해서 보관해요. 신고 준비는 실제 기록을 기준으로 해요.</p><Row label={`${s.tax.year}년 실제 일반계좌 세전 배당`} value={money(actualTax.gross)} />{s.receipts.map(r => <ListRow key={r.id} onClick={() => editReceipt(r)} contents={<div className="row-label">{s.positions.find(p => p.id === r.positionId)?.name}<small>{r.date}</small></div>} right={money(r.gross-r.foreignTax-r.nationalTax-r.localTax)} />)}<div className="inset"><Button display="block" variant="weak" disabled={!s.positions.length} onClick={() => editReceipt()}>수령 기록 추가하기</Button>{s.receipts.length > 0 && <Notice>{actualTax.reason}<p>기록한 일반계좌 배당만 합산해요. 미기록 소득은 포함하지 않으며 ISA·연금 내 배당은 제외해요.</p>{actualTax.complete ? `기록 기준 배당 사용 가능액 ${money(actualTax.usable)}` : '기록 기준 최종 세금 계산 미완료'}</Notice>}</div></Section>
    <Section title="신고 준비 확인하기"><div className="inset"><p className="help">{s.tax.year}년 귀속 → {s.tax.year+1}년 신고 · 최종 기간은 국세청 공지를 확인해 주세요.</p>{filingSteps.map((step,i) => <div className="filing-step" key={step.id}><Check checked={s.checklist.includes(`${s.tax.year}:${step.id}`)} onChange={v => update({ ...s,checklist:v ? [...s.checklist,`${s.tax.year}:${step.id}`] : s.checklist.filter(k => k !== `${s.tax.year}:${step.id}`) })}><strong>{i+1}. {step.title}</strong></Check><p>{step.text}</p></div>)}<Button display="block" onClick={() => openUrl('https://www.hometax.go.kr')}>홈택스에서 신고 준비하기</Button><Button display="block" color="dark" variant="weak" onClick={() => openUrl('https://www.wetax.go.kr')}>위택스 확인하기</Button></div></Section>
    <Section title="계산 기준과 공식 출처"><div className="inset"><p className="help">{TAX_VERSION} · 법령 확인 2026.10.10<br />확정 신고세액이 아니에요. 건강보험료 자동계산은 제공하지 않아요.</p>{sources.map(source => <button className="source-link" key={source.url} onClick={() => openUrl(source.url)}>{source.title}<span>↗</span></button>)}</div></Section>
  </>;
}
