import { expect, test } from '@playwright/test';
test('예시·건보료 제외/입력/0원·저장 복원·실제 기록 분리', async ({ page }) => {
  const errors:string[]=[]; page.on('pageerror',e => errors.push(e.message));
  await page.goto('/'); await page.getByRole('button',{ name:'예시로 체험하기' }).click();
  await expect(page.getByTestId('monthly-income')).toHaveText('352,500원');
  await page.getByText('실제 수령 기록',{exact:true}).click();
  await expect(page.getByText('아직 이 귀속연도의 일반계좌 수령 기록이 없어요.',{exact:false})).toBeVisible();
  await page.getByRole('button',{ name:'FIRE',exact:true }).click();
  await page.getByLabel('건강보험료 계산 방식').selectOption('manual');
  await expect(page.getByText('건강보험료를 입력해 주세요',{ exact:true }).first()).toBeVisible();
  await page.getByLabel('월 건강보험료',{ exact:true }).fill('200000');
  await page.getByLabel('건강보험료 계산 방식').selectOption('exclude');
  await expect(page.getByText('건강보험료를 제외한 결과예요',{ exact:true })).toBeVisible();
  await page.getByRole('button',{ name:'저장하기',exact:true }).click();
  await page.reload(); await page.getByRole('button',{ name:'FIRE',exact:true }).click();
  await page.getByLabel('건강보험료 계산 방식').selectOption('manual');
  await expect(page.getByLabel('월 건강보험료',{ exact:true })).toHaveValue('200000');
  await page.getByLabel('월 건강보험료',{ exact:true }).fill('0');
  await expect(page.getByText('건강보험료 월 0원을 포함해요')).toBeVisible();
  await page.screenshot({ path:'reports/fire-375.png',fullPage:true });
  await page.getByRole('button',{ name:'세금·신고',exact:true }).click();
  await page.screenshot({ path:'reports/tax-375.png',fullPage:true });
  await page.getByRole('button',{ name:'수령 기록 추가하기' }).click();
  await page.getByLabel('세전 배당금',{ exact:true }).fill('100000');
  await page.getByLabel('국내 국세 원천징수',{ exact:true }).fill('14000');
  await page.getByLabel('국내 지방세 원천징수',{ exact:true }).fill('1400');
  await page.getByRole('button',{ name:'수령 기록 반영하기' }).click();
  await expect(page.getByText('84,600원',{ exact:true })).toBeVisible();
  await page.getByRole('button',{ name:'내 배당',exact:true }).click();
  await expect(page.getByTestId('monthly-income')).toHaveText('352,500원');
  await page.getByText('실제 수령 기록',{exact:true}).click();
  await expect(page.getByRole('img',{name:/월별 기록한 실제 입금액/})).toHaveAttribute('aria-label',/1월 84,600원/);
  await page.screenshot({ path:'reports/dashboard-375.png',fullPage:true });
  expect(errors).toEqual([]);
});
test('자동조회 없이 직접 입력·잘못된 계좌 상품·저장 실패 재시도', async ({ page }) => {
  await page.goto('/'); await page.getByRole('button',{ name:'종목 추가하기',exact:true }).click();
  await page.getByLabel('종목 이름',{ exact:true }).fill('직접 입력 자산');
  await page.getByLabel('보유 수량',{ exact:true }).fill('100');
  await page.getByLabel('현재 주당 가격',{ exact:true }).fill('10000');
  await page.getByLabel('연간 주당 배당금',{ exact:true }).fill('1000');
  await expect(page.getByText('DART 공시 배당 조회하기',{ exact:true })).toHaveCount(0);
  await page.getByRole('button',{ name:'종목 반영하기' }).click();
  await page.evaluate(() => { const original=Storage.prototype.setItem; (window as any).restoreStorage=() => { Storage.prototype.setItem=original; }; Storage.prototype.setItem=() => { throw new Error('저장 공간이 부족해요'); }; });
  await page.getByRole('button',{ name:'저장하기',exact:true }).click();
  await expect(page.getByRole('alert')).toContainText('저장 공간');
  await page.evaluate(() => (window as any).restoreStorage());
  await page.getByRole('button',{ name:'저장하기',exact:true }).click();
  await expect(page.getByRole('status')).toHaveText('저장했어요');
  await page.getByText('계좌·환율 관리하기').click();
  await page.getByRole('button',{ name:'계좌 추가하기' }).click();
  await page.getByLabel('계좌 이름').fill('내 ISA'); await page.getByLabel('계좌 종류').selectOption('isa');
  await page.getByRole('button',{ name:'계좌 반영하기' }).click();
  await page.getByRole('button',{ name:'종목 추가하기',exact:true }).click();
  await page.getByLabel('종목 이름').fill('해외 ETF'); await page.getByLabel('계좌',{ exact:true }).selectOption({ label:'내 ISA' });
  await page.getByLabel('상장 시장·통화').selectOption('US'); await page.getByLabel('상품 종류').selectOption('etf');
  await page.getByLabel('보유 수량').fill('1'); await page.getByLabel('현재 주당 가격').fill('100');
  await page.getByRole('button',{ name:'종목 반영하기' }).click();
  await expect(page.getByRole('alert')).toContainText('국내 상장 ETF');
});
test('작은 화면·큰 글자·탭과 뒤로가기·손상 기록 보존', async ({ page }) => {
  for (const width of [360,375,430]) {
    await page.setViewportSize({ width,height:812 }); await page.goto('/');
    await expect(page.getByRole('navigation',{ name:'주요 화면' })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  await page.getByRole('button',{ name:'예시로 체험하기' }).click();
  await page.getByRole('button',{ name:'FIRE',exact:true }).click();
  await page.evaluate(() => { document.querySelectorAll<HTMLElement>('h1,h2,p,span,strong,button,input,select,summary').forEach(e => { e.style.fontSize=`${parseFloat(getComputedStyle(e).fontSize)*1.35}px`; }); });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button',{ name:'뒤로가기' }).click();
  await expect(page.getByTestId('monthly-income')).toBeVisible();
  await page.evaluate(() => localStorage.setItem('dividend-fire:v1:browser','{"schemaVersion":99}'));
  await page.reload(); await expect(page.getByRole('alert')).toContainText('덮어쓰지');
  expect(await page.evaluate(() => localStorage.getItem('dividend-fire:v1:browser'))).toBe('{"schemaVersion":99}');
});
